/*
 * DGSPreviewCanvas.java
 *
 * Created on March 30, 2009, 3:35 PM
 */
package dgspreviewer;

import java.awt.*;
import java.beans.*;

/**
 *
 * @author  dwimsey
 */
public class DGSPreviewCanvas extends javax.swing.JPanel implements java.awt.event.ComponentListener {

	public interface NotificationMethods {
		public void logEvent(int LogLevel, String Message);
		public void statusMessage(int LogLevel, String Message);
		public void propertyChangeNotification(PropertyChangeEvent evt);
	}

	public enum DisplayMode {
		Draft,
		PNG,
		GIF,
		JPEG,
		TIFF,
		PDF;
	};
	private DisplayMode displayMode;
	private Color backgroundColor;
	private String lastLoadedURI = null;
	private String lastLoadedDGSPackageURI = null;
	protected NotificationMethods notificationMethods = null;
	private java.beans.PropertyChangeListener pcListener = null;
	private DGSPreviewCanvasLoaderWorker workerThread = null;
	public ImageProcessor.ProcessingEngine.ProcessingEngine pEngine = null;

	/** Creates new form DGSPreviewCanvas */
	public DGSPreviewCanvas() {
		this.displayMode = DisplayMode.GIF;
		this.backgroundColor = new Color(0xFFFFFFFF);
		this.initComponents();
		this.addComponentListener(this);
		// do the initial layer ordering
		this.updateLayers();
	}

	private void updateLayers() {
		switch (displayMode) {
			case Draft:
				this.layers.setLayer(renderedCanvas, 0);
				this.layers.setLayer(draftCanvas, 1);
				break;
			case PNG:
			case GIF:
			case JPEG:
			case TIFF:
				this.layers.setLayer(draftCanvas, 0);
				this.layers.setLayer(renderedCanvas, 1);
				break;
			case PDF:
				break;
		}
	}

	private synchronized boolean cancelWorker(boolean mayInterruptIfNeeded) {
		if (workerThread != null) {
			if (!workerThread.isDone()) {
				workerThread.cancel(mayInterruptIfNeeded);
				return (true);
			}
			workerThread = null;
		}
		return (false);
	}

	public void loadUri(String fileUri, String dgsPackageFile, NotificationMethods newMethods) {
		this.cancelWorker(true);
		lastLoadedURI = fileUri;
		lastLoadedDGSPackageURI = dgsPackageFile;
		notificationMethods = newMethods;
		if (lastLoadedURI == null) {
			renderedCanvas.image = null;
			renderedCanvas.repaint();
			draftCanvas.setURI(null);
			return;
		}
		workerThread = new DGSPreviewCanvasLoaderWorker(this, pEngine, fileUri, dgsPackageFile);
		if (pcListener == null) {
			pcListener = new java.beans.PropertyChangeListener() {

				@Override
				public void propertyChange(PropertyChangeEvent evt) {
					if (notificationMethods != null) {
						notificationMethods.propertyChangeNotification(evt);
					}
				}
			};
		}
		workerThread.addPropertyChangeListener(pcListener);
		workerThread.execute();
	}

	public DisplayMode getDisplayMode() {
		return (this.displayMode);
	}

	public void setDisplayMode(DisplayMode newMode) {
		if (newMode != this.displayMode) {
			boolean loadInProgress = this.cancelWorker(true);
			this.displayMode = newMode;
			this.updateLayers();
			renderedCanvas.image = null;
			draftCanvas.setDocument(null);
			if (lastLoadedURI != null) {
				// refresh the loaded image
				this.loadUri(lastLoadedURI, lastLoadedDGSPackageURI, notificationMethods);
			}
		}
	}

	public java.awt.Color getBackgroundColor() {
		return (this.backgroundColor);
	}

	public void setBackgroundColor(java.awt.Color newColor) {
		this.backgroundColor = newColor;
		if(this.backgroundColor == null) {
			this.backgroundColor = new java.awt.Color(0xFFFFFFFF);
		}
		this.renderedCanvas.setBackgroundColor(this.backgroundColor);
		this.draftCanvas.setBackground(this.backgroundColor);
	}

	@Override
	public void componentHidden(java.awt.event.ComponentEvent e) {
	}

	@Override
	public void componentMoved(java.awt.event.ComponentEvent e) {
	}

	@Override
	public void componentResized(java.awt.event.ComponentEvent e) {
		if(e.getSource() == this) {
			java.awt.Rectangle r = this.getBounds();
			draftCanvas.setBounds(r);
			renderedCanvas.setBounds(r);
		}
	}

	@Override
	public void componentShown(java.awt.event.ComponentEvent e) {
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layers = new javax.swing.JLayeredPane();
        draftCanvas = new org.apache.batik.swing.JSVGCanvas();
        renderedCanvas = new dgspreviewer.DGSPreviewerPanel();

        setName("DGSPreviewCanvas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(32676, 32676));

        layers.setName("layers"); // NOI18N
        layers.setPreferredSize(new java.awt.Dimension(32676, 32676));

        draftCanvas.setName("draftCanvas"); // NOI18N

        javax.swing.GroupLayout draftCanvasLayout = new javax.swing.GroupLayout(draftCanvas);
        draftCanvas.setLayout(draftCanvasLayout);
        draftCanvasLayout.setHorizontalGroup(
            draftCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        draftCanvasLayout.setVerticalGroup(
            draftCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        draftCanvas.setBounds(0, 0, -1, -1);
        layers.add(draftCanvas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        renderedCanvas.setName("renderedCanvas"); // NOI18N
        renderedCanvas.setPreferredSize(new java.awt.Dimension(32676, 32676));

        javax.swing.GroupLayout renderedCanvasLayout = new javax.swing.GroupLayout(renderedCanvas);
        renderedCanvas.setLayout(renderedCanvasLayout);
        renderedCanvasLayout.setHorizontalGroup(
            renderedCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32676, Short.MAX_VALUE)
        );
        renderedCanvasLayout.setVerticalGroup(
            renderedCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32676, Short.MAX_VALUE)
        );

        renderedCanvas.setBounds(0, 0, -1, -1);
        layers.add(renderedCanvas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected org.apache.batik.swing.JSVGCanvas draftCanvas;
    private javax.swing.JLayeredPane layers;
    protected dgspreviewer.DGSPreviewerPanel renderedCanvas;
    // End of variables declaration//GEN-END:variables
}
